### PR TITLE
Server.js

### PR DESCRIPTION
**Pull request by stephenisau**
This pull request includes a

- [ ] Bug fix
- [X] New feature
- [X] Translation

The following changes were made

- Moved the logic for port listening into an individual server.js file

If this is related to an existing ticket, include a link to it as well.

### CODE REVIEW

**Comment by mmmaaatttttt** [comment]
same comment as your other PR. @stephenisau Now that #33 is merged, can you please update this PR with the latest changes from master? should help clean up the diff. looks like there will be some merge conflicts, not sure why.

**Comment by stephenisau** [comment]
@mmmaaatttttt should I close this one as well?

**Comment by mmmaaatttttt** [comment]
@stephenisau up to you, you could close and open a fresh one or try merging the latest from master. To keep things simple maybe wait until #34 is merged first.

**Comment by stephenisau** [comment]
Added changes in this PR to [#34](https://github.com/rithmschool/numbers_api/pull/34)

**Pull request closed without merging**
