### PR TITLE
Remove ruby dependencies

### PR DESCRIPTION
**Pull request by paigegodfrey**
This pull request includes a

- [ ] Bug fix
- [ ] New feature
- [X] Translation

The following changes were made

- Added node-sass for static asset compilation
- Removed compass mixins and translated into css3 compatible syntax (images shown below)

If this is related to an existing ticket, include a link to it as well.
- Resolves issue #6 

page_top
page_bottom

### CODE REVIEW

**Review by mmmaaatttttt — COMMENTED** [review]
@paigegodfrey this looks great, thank you for taking care of this! only question i have is what this means for getting started. do you need to do something like `npm run scss` and then `npm start` in order to get things working? we'll probably need to update the getting started wiki. let me know what this looks like.

**Comment by paigegodfrey** [comment]
@mmmaaatttttt thanks! @ngjamesng was a huge help and found most of the documentation on how to do this. For the Getting Started Wiki, we just need to replace `compass compile public/` with `npm run scss `. I can update that as well if you want. 

Also for issue #8, I think it's easiest to work off this version (with ruby removed) since there was a dependency on `compass_twitter_bootstrap `. Please let me know if I should update my master branch with these changes.

**Comment by ngjamesng** [comment]
[Getting Started](https://github.com/rithmschool/numbers_api/wiki/Getting-Started) has been updated to reflect the change of instructions proposed on this PR!

**Review by mmmaaatttttt — APPROVED** [review]

**Comment by mmmaaatttttt** [comment]
@paigegodfrey @ngjamesng - just approved and merged. Thanks again!

**Pull request merged**
